# Определение группы серверов для балансировки нагрузки
# В данном случае у нас только один бэкенд-сервер
upstream bot_backend {
    # Адрес и порт бэкенд-сервера
    # 'backend' - это имя сервиса в Docker Compose, 8000 - порт
    server backend:8000;
}

# Основной блок конфигурации сервера
server {
    # Прослушивание 80 порта (HTTP)
    listen 80;

    # Обработка всех запросов к корневому пути
    location / {
        # Проксирование запросов на бэкенд
        proxy_pass http://bot_backend;
        
        # Передача реального IP-адреса клиента
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Передача оригинального хоста
        proxy_set_header Host $host;
        
        # Отключение перенаправлений
        proxy_redirect off;
    }

    # Обработка запросов к статическим файлам
    location /staticfiles/ {
        # Путь к статическим файлам в контейнере
        alias /usr/src/app/staticfiles/;
    }
}